# Generated by Django 5.1.6 on 2025-02-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespersons',
            options={'managed': False},
        ),
    ]
