# Generated by Django 5.1.6 on 2025-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_track_alter_salespersons_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('AlbumId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=35)),
                ('ArtistId', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Track',
                'managed': False,
            },
        ),
    ]
