# Generated by Django 5.1.6 on 2025-02-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_album'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
    ]
